### ISSUE TITLE
Show does not delete after "Take action after days" = 0

### ISSUE THREAD

**Issue by truncsphere** [jorenn92/Maintainerr#1140]
**Describe the bug**
I have a rule that deletes stale shows that haven't been watched in over 1 year. Currently 2 shows fit this description. I have watched the countdown reach 0 twice and neither time did it delete the show. Instead the logs show it's been removed from the collection and then it re-adds and restarts the timer. 

**Expected behavior**
To delete said shows after 30 days. 

**Screenshots**
![image](https://github.com/jorenn92/Maintainerr/assets/16292618/848c2c95-77f4-4304-98d1-8f4c37cc3750)

**Device (please complete the following information):**
 - Maintainerr version 2.0.4

**Other notes**
I have a rule to delete movies not watched after X years and it removes these with no issues.

**Comment by adampetrovic** [comment]
Also have the same problem, running on both older versions and the most recent version. The logs aren't overly helpful.

**Comment by jorenn92** [comment]
Hey, something else re-adds the media. Mostly this is a due to Overseerr’s auto watchlist download feature. Make sure something like that isn’t enabled

**Comment by adampetrovic** [comment]
Overseerr works off the Plex Watchlist. None of these items are on that list.

![screenshot_2024_06_22_19_07_43](https://github.com/jorenn92/Maintainerr/assets/88030/3df06d82-bd3c-42e6-8911-c2d7288da286)

**Comment by truncsphere** [comment]
I don't use watchlists with Overseer so the media is not being re-added. It never gets deleted.

**Comment by truncsphere** [comment]
Any update on this issue?

**Comment by jorenn92** [comment]
Hey, Sorry for the late reply. I haven't seen any related reports and haven't been able to replicate this myself. So i'm actually unsure what's going on. Do you happen to have logs from Plex, Sonarr, and perhaps Overseerr during the deletion timeframe?

I think it has something to do with a failure to fetch the tvdb id, which is used for removal through Sonarr. Altough it should log a message when this is the case. 

This error is due to a failure while fetching the tvdb ID from tmdb. But there are a few fallback mechanisms, so it's possible one of those did find the ID. 
`[maintainerr] | 22/06/2024 03:50:12  [DEBUG] [undefined] GET request failed: AxiosError: Request failed with status code 500`

**Comment by truncsphere** [comment]
So this just happened to happen again this morning. Shows got removed by Maintainer, but are still on Plex. The shows were re-added and the counter started again at 30 days. 

I check Sonarr logs and didn't see anything around the time these were supposed to be deleted. The closest I found was below
`2024-07-16 08:58:47.8|Info|RefreshEpisodeService|Starting episode info refresh for: [341164][Yellowstone (2018)]
2024-07-16 08:58:48.4|Info|RefreshEpisodeService|Finished episode refresh for series: [341164][Yellowstone (2018)].
2024-07-16 08:58:48.4|Info|DiskScanService|Scanning Yellowstone (2018)
2024-07-16 08:58:48.4|Info|DiskScanService|Completed scanning disk for Yellowstone (2018)`

Overseer shows the following
![image](https://github.com/user-attachments/assets/dc0c1d7f-e4d6-4c99-9820-83dd31d9fe26)

However these are just refreshes and nothing re-downloaded to my server.

**Comment by jorenn92** [comment]
I pushed a few changes that might fix your issue. If not, it'll hopefully log more 'debug' level info this time,

You can try it out with the 'ghcr.io/jorenn92/maintainerr:main' image. This image gets build after each git change.
I don't recommend to stay on it for long, since this image might not stay stable, and after big changes you might not always be able to roll back to the latest release version. However, for now it'll be safe.

**Comment by truncsphere** [comment]
> I pushed a few changes that might fix your issue. If not, it'll hopefully log more 'debug' level info this time,
> 
> You can try it out with the 'ghcr.io/jorenn92/maintainerr:main' image. This image gets build after each git change. I don't recommend to stay on it for long, since this image might not stay stable, and after big changes you might not always be able to roll back to the latest release version. However, for now it'll be safe.

I just installed the main version. Will let you know in 4 days what happens.

**Comment by jorenn92** [comment]
> Unmonitored season(s)

Unfortunately, the above log seems fine. It successfully unmonitored the show and removed all episodes. At least, the API calls to Sonarr were successful from Maintainer's point of view.

Did you enable the 'DEBUG=true' flag in your environment variables? If not, maybe that'll give us some more info. If you did enable it, it looks like everything went alright.

Also, could you check the history of an episode of these shows in Sonarr to make sure it wasn't redownloaded?

I did push some minor changes today, one of which fixes a small issue where seasons would stay monitored while the show is unmonitored. But I don't think this has any functional impact, since Sonarr wouldn't download episodes of an unmonitored show anyway.

**Comment by truncsphere** [comment]
I did not have DEBUG enabled. 

Sonarr does not re-download the shows (I would get a notification at several stages of the download/addition to Plex). 

I've deleted the shows manually for now.

**Comment by adampetrovic** [comment]
With `DEBUG` enabled, lots of 500 errors for legitimate shows. I'm guessing this approach is an unreliable one.

```
[maintainerr] | 03/08/2024 21:36:41  [DEBUG] [ExternalAPI] GET request to /tv/8519/season/5 failed: AxiosError: Request failed with status code 500
[maintainerr] | 03/08/2024 21:36:41  [DEBUG] [OverseerrGetterService] Couldn't fetch season data for 'Man v. Food' season 5 from Overseerr. As a result, unreliable results are expected.
[maintainerr] | 03/08/2024 21:36:41  [DEBUG] [ExternalAPI] GET request to /tv/8519/season/6 failed: AxiosError: Request failed with status code 500
[maintainerr] | 03/08/2024 21:36:41  [DEBUG] [OverseerrGetterService] Couldn't fetch season data for 'Man v. Food' season 6 from Overseerr. As a result, unreliable results are expected.
[maintainerr] | 03/08/2024 21:36:42  [DEBUG] [ExternalAPI] GET request to /tv/8519/season/7 failed: AxiosError: Request failed with status code 500
[maintainerr] | 03/08/2024 21:36:42  [DEBUG] [OverseerrGetterService] Couldn't fetch season data for 'Man v. Food' season 7 from Overseerr. As a result, unreliable results are expected.
[maintainerr] | 03/08/2024 21:36:42  [DEBUG] [ExternalAPI] GET request to /tv/8519/season/8 failed: AxiosError: Request failed with status code 500
[maintainerr] | 03/08/2024 21:36:42  [DEBUG] [OverseerrGetterService] Couldn't fetch season data for 'Man v. Food' season 8 from Overseerr. As a result, unreliable results are expected.
[maintainerr] | 03/08/2024 21:36:43  [DEBUG] [ExternalAPI] GET request to /tv/8519/season/9 failed: AxiosError: Request failed with status code 500
[maintainerr] | 03/08/2024 21:36:43  [DEBUG] [OverseerrGetterService] Couldn't fetch season data for 'Man v. Food' season 9 from Overseerr. As a result, unreliable results are expected.
[maintainerr] | 03/08/2024 21:36:43  [DEBUG] [ExternalAPI] GET request to /tv/8519/season/10 failed: AxiosError: Request failed with status code 500
[maintainerr] | 03/08/2024 21:36:43  [DEBUG] [OverseerrGetterService] Couldn't fetch season data for 'Man v. Food' season 10 from Overseerr. As a result, unreliable results are expected
```

**Comment by jorenn92** [comment]
Okay, hopefully you won't run into it again! But If you do, could you share a log file when the DEBUG flag has been set?

**Comment by DataBitz** [comment]
I'm seeing a similar problem, the files are deleted from disks and it is removed from Sonarr. However the problem is that the TV shows are still showing in Plex, though when I try to play a show the files are unavailable.
When I rerun the runs in maintainerr I think it is picking up the unavailable TV shows from Plex.
Still testing but this may help if anyone else hits this.

**Comment by DataBitz** [comment]
Another quick update, I have " Empty trash automatically after every scan" in Plex Library settings disabled.
Once I emptied the trash in Plex manually it stopped coming back.

**Comment by jorenn92** [comment]
> Another quick update, I have " Empty trash automatically after every scan" in Plex Library settings disabled. Once I emptied the trash in Plex manually it stopped coming back.

Good catch! I can confirm your theory: If the item is still showing in Plex, Maintainerr assumes it's still available, which is why it keeps coming back.

**Comment by DataBitz** [comment]
What's the solution in the scenario, could maintainerr be set-up to take into account if the content is available or not?

**Comment by appiekap653** [comment]
I have a similar problem. Mostly with movies.
When the timer in maintainerr reaches 0, maintainerr logs shows this: 

![Screenshot_20240904_174720_Firefox.jpg](https://github.com/user-attachments/assets/e00dbaae-dca8-4705-8bf4-788cef8137d0)

When looking at Radarr, there are no API calls to remove the files and delete the movie from Radarr.

It seems like maintainerr is just skipping the whole Radarr part but removes the movie from itself, then at the next scan, he re-adds the movie again. 

This has been happening for a long time now in multiple maintainerr versions. 

When looking at the XML from Plex for this movie, it does have all the necessary IDs:

```
<Guid id="imdb://tt29081098"/>
<Guid id="tmdb://1165403"/>
<Guid id="tvdb://349372"/>
```

**Comment by jorenn92** [comment]
I

> I have a similar problem. Mostly with movies. When the timer in maintainerr reaches 0, maintainerr logs shows this:
> 
> ![Screenshot_20240904_174720_Firefox.jpg](https://private-user-images.githubusercontent.com/29512159/366771404-35eda68d-6d3f-44f6-908b-a918caab3457.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTEyMTAsIm5iZiI6MTcyNjIxMDkxMCwicGF0aCI6Ii8yOTUxMjE1OS8zNjY3NzE0MDQtMzVlZGE2OGQtNmQzZi00NGY2LTkwOGItYTkxOGNhYWIzNDU3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA3MDE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0Y2I1MjRmNzkzZjM4ZDM4ZWQxN2I2ODBkMzJhNzk5NzUwZTUyZTFmODY0YjhiMTJhZDBlMmRmNzZkMDNkOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vIG-8qZzBPzQctH16C17BM-TsMUNES9jQm2HEqSiH1o)
> 
> When looking at Radarr, there are no API calls to remove the files and delete the movie from Radarr.
> 
> It seems like maintainerr is just skipping the whole Radarr part but removes the movie from itself, then at the next scan, he re-adds the movie again. Occasionally the logs from Maintainerr shows `removed come fly with me` (like on 8-8-2024 in above screenshot), but does not show `Successfully handled come fly with me`.
> 
> This has been happening for a long time now in multiple maintainerr versions.
> 
> When looking at the XML from Plex for this movie, it does have all the necessary IDs:
> 
> ```
> <Guid id="imdb://tt29081098"/>
> <Guid id="tmdb://1165403"/>
> <Guid id="tvdb://349372"/>
> ```

Do you have logs of these executions as well? This looks quite bizarre. It seems that something else is removing the item from the collection between runs, which causes Maintainer to re-add it. (However, when manually removed from the Plex collection, Maintainerr should create an exclusion)

Regarding the 'Removed ...' log line without a corresponding 'Successfully handled ...' message: This can occur if the item no longer matches the rule criteria before the removal takes place. In such cases, the item is removed again, and you'll only see the 'removed' message.

**Comment by ydkmlt84** [comment]
> I'm running into this issue as well. I have a library of YouTube videos that is exhibiting the same behavior. Items will get removed and then re-added to the collection. They are not getting deleted. Here is an example. You can see this is getting removed and then re-added daily:
> 
> ![Screenshot 2024-10-17 at 11 48 05 AM](https://private-user-images.githubusercontent.com/15266520/377540320-0187c2ba-d7f9-42ed-a5f4-2dd8c02f0bb0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTQyNzAsIm5iZiI6MTcyOTIxMzk3MCwicGF0aCI6Ii8xNTI2NjUyMC8zNzc1NDAzMjAtMDE4N2MyYmEtZDdmOS00MmVkLWE1ZjQtMmRkOGMwMmYwYmIwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDAxMTI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MTZkY2UzZjI3ZjhkMTJlNjIxMzM0YzU2OTRiZjliMzhhZjc4Yzc5MGU1NjliMzMzMGE1ZTY1ODZhNTkwOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eXVSGzkvU4lMl3ciKkm8Xl88QoWzVcgwH83vXUWctd0)

Are you seeing anything in your Sonarr logs? Are there any entries about deleting or failure to delete? This has happened to a few people in the past, and the answer was usually a change to the hostname they were using in the Sonarr/Radarr settings of Maintainerr. I even had this problem when I started because I was using the docker container hostname. When I switched to the IP address it started to work. Even though my connection test were coming back as successful.

**Comment by macstainless** [comment]
> > I'm running into this issue as well. I have a library of YouTube videos that is exhibiting the same behavior. Items will get removed and then re-added to the collection. They are not getting deleted. Here is an example. You can see this is getting removed and then re-added daily:
> > ![Screenshot 2024-10-17 at 11 48 05 AM](https://private-user-images.githubusercontent.com/15266520/377540320-0187c2ba-d7f9-42ed-a5f4-2dd8c02f0bb0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTQyNzAsIm5iZiI6MTcyOTIxMzk3MCwicGF0aCI6Ii8xNTI2NjUyMC8zNzc1NDAzMjAtMDE4N2MyYmEtZDdmOS00MmVkLWE1ZjQtMmRkOGMwMmYwYmIwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDAxMTI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MTZkY2UzZjI3ZjhkMTJlNjIxMzM0YzU2OTRiZjliMzhhZjc4Yzc5MGU1NjliMzMzMGE1ZTY1ODZhNTkwOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eXVSGzkvU4lMl3ciKkm8Xl88QoWzVcgwH83vXUWctd0)
> 
> Are you seeing anything in your Sonarr logs? Are there any entries about deleting or failure to delete? This has happened to a few people in the past, and the answer was usually a change to the hostname they were using in the Sonarr/Radarr settings of Maintainerr. I even had this problem when I started because I was using the docker container hostname. When I switched to the IP address it started to work. Even though my connection test were coming back as successful.

In my situation, my YouTube Plex library is not associated with Sonarr, so there's no logs. Those items are imported via a script into my Plex library. My understanding is Maintainarr isn't dependent on the item being located in Sonarr / Radarr and will delete from Plex as long as it meets the criteria in the library.

**Comment by macstainless** [comment]
> > In my situation, my YouTube Plex library is not associated with Sonarr, so there's no logs. Those items are imported via a script into my Plex library. My understanding is Maintainarr isn't dependent on the item being located in Sonarr / Radarr and will delete from Plex as long as it meets the criteria in the library.
> 
> Hi @macstainless, that should be the case yes. I presume you have **Allow media deletion** enabled in Plex?

Yes I do have that enabled on Plex.

**Comment by lediszep** [comment]
I have the same issue, media is not being deleted for the past months is there a solution or has it been fixed?

**Comment by ydkmlt84** [comment]
> I have the same issue, media is not being deleted for the past months is there a solution or has it been fixed?

I would like to see what we can get figured out on Discord. Mind coming over there and we can take a look?

**Comment by ben-propflo** [comment]
@macstainless For your issue, you should now be able to select 'None' in the Radarr/Sonarr server dropdown in the rule config. When it comes to removing it should call the Plex API to delete the media from disk. This was sort of the case before but I don't think it worked at all if you had configured a Sonarr/Radarr server.

**Comment by benscobie** [comment]
@macstainless For your issue, you should now be able to select 'None' in the Radarr/Sonarr server dropdown in the rule config. When it comes to removing it should call the Plex API to delete the media from disk. This was sort of the case before but I don't think it worked at all if you had configured a Sonarr/Radarr server.

**Comment by cliny** [comment]
I have had this same issue for a while now. Most of the time it will not "Successfully handled "movie/tv show"" when "Take action after days*" is set to zero. 

I have a bunch of TV shows and movies to be deleted via sonarr/radarr, but strangely it just doesn't "handle" most. The "0" on the cover art then starts going into negatives (-1, -2) as days go on.

On 2.8.0 cuurently.

This is my movies rule, for example, to replicate:

-name: delete_movies
-library: Movies
-radarr server: Radarr
-take action after days: 0
-show on library recommended: no
-show on home: no
-add list exclusions: no
-force reset overseerr: yes
-import:
mediaType: MOVIES
rules:
  - "0":
      - firstValue: Tautulli.addDate
        action: BEFORE
        customValue:
          type: custom_days
          value: "30"
  - "1":
      - operator: AND
        firstValue: Tautulli.lastViewedAt
        action: BEFORE
        customValue:
          type: custom_days
          value: "30"
      - operator: OR
        firstValue: Tautulli.viewCount
        action: EQUALS
        customValue:
          type: number
          value: 0

**Comment by benscobie** [comment]
> I have a bunch of TV shows and movies to be deleted via sonarr/radarr, but strangely it just doesn't "handle" most. The "0" on the cover art then starts going into negatives (-1, -2) as days go on.

[Enable debug logging](https://docs.maintainerr.info/latest/Installation/#enabling-debug-logging_1), run Handle collections, check that the above issue occurs and then attach your logs please.

**Comment by cliny** [comment]
> > I have a bunch of TV shows and movies to be deleted via sonarr/radarr, but strangely it just doesn't "handle" most. The "0" on the cover art then starts going into negatives (-1, -2) as days go on.
> 
> [Enable debug logging](https://docs.maintainerr.info/latest/Installation/#enabling-debug-logging_1), run Handle collections, check that the above issue occurs and then attach your logs please.

It deleted one tv show properly, then presented this error:

```
[maintainerr] | 31/01/2025 11:30:09  [INFO] [CollectionWorkerService] Start handling all collections
[maintainerr] | 31/01/2025 11:30:09  [INFO] [CollectionWorkerService] Handling collection 'delete_tv_shows'
[maintainerr] | 31/01/2025 11:30:09  [INFO] [CollectionsService] Removing media with id 75853 from collection..
TypeError: Cannot read properties of undefined (reading 'ratingKey')
    at CollectionWorkerService.handleMedia (/opt/app/server/modules/collections/collection-worker.service.js:276:67)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CollectionWorkerService.execute (/opt/app/server/modules/collections/collection-worker.service.js:79:25)
```

**Comment by benscobie** [comment]
Thanks, I see the issue, I'll get a fix up soon. One of your TV shows can't be found in Sonarr so it attempts to delete from disk via Plex as a fallback, but this is broken. If you know a TV show that's been stuck in there, try Fix Match on it in Plex. Plex is likely returning an incorrect TVDB ID at the moment.

**Comment by cliny** [comment]
> Thanks, I see the issue, I'll get a fix up soon. One of your TV shows can't be found in Sonarr so it attempts to delete from disk via Plex as a fallback, but this is broken. If you know a TV show that's been stuck in there, try Fix Match on it in Plex. Plex is likely returning an incorrect TVDB ID at the moment.

Thank you, the 100+ movies and 10+ tv shows were handled (deleted from sonarr/radarr) when I ran it that time. 

Beforehand, I looked through sonarr/radarr and plex too, and they all seem to be matched correctly. In my plex server settings, under 'Library', I have disabled 'Allow media deletion' tho
